In [51]:
import numpy as np

In [ ]:
NUMPY INDEXING AND SLICING OF VECTORS


In [53]:
arr=np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [56]:
arr[8]     #array indexing

np.int64(19)

In [57]:
arr[1:6]    #array slicing

array([12, 13, 14, 15, 16])

In [58]:
arr_slice=arr[1:10:2]
arr_slice     

array([12, 14, 16, 18])

In [59]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [62]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [63]:
arr[0]     #print row only

array([1, 2, 3, 4, 5])

In [64]:
arr[0,0]          #finding element from table by using row and col

np.int64(1)

In [65]:
arr[0,4]

np.int64(5)

In [66]:
arr[-1,-1]

np.int64(30)

In [68]:
#slicing 2row and 2column or %more
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [69]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [71]:
#practice
slicing=arr[3:6,3:5]
slicing

array([[19, 20],
       [24, 25],
       [29, 30]])

In [72]:
arr[: ,3]

array([ 4,  9, 14, 19, 24, 29])

In [73]:
arr=np.arange(11,31)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [74]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [75]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])