In [2]:
import numpy as np

In [8]:
list=[2,3,4,5.3,"santosh"]
list

[2, 3, 4, 5.3, 'santosh']

In [5]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr=np.ones((5,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [21]:
arr=np.random.rand(10)
arr

array([0.02312536, 0.64214982, 0.650998  , 0.48429941, 0.51426325,
       0.93628289, 0.99073766, 0.04802193, 0.3614315 , 0.72897473])

In [23]:
arr=np.random.randn(4)
arr


array([ 1.28530558, -0.48971912,  0.07169996, -1.46140937])

In [31]:
arr=np.random.randint(1,10,11)
arr

array([7, 5, 6, 1, 2, 7, 4, 5, 5, 4, 5], dtype=int32)

In [33]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.size

9

In [35]:
arr.shape

(3, 3)

In [36]:
arr.dtype

dtype('int64')

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.sum()

np.int64(45)

In [39]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [40]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [41]:
 arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [45]:
arr.argmax()   #last index no

np.int64(8)

In [46]:
arr.argmin()

np.int64(0)

In [47]:
arr.std()

np.float64(2.581988897471611)

In [48]:
arr.mean()

np.float64(5.0)