In [2]:
import numpy as np

In [ ]:
Arithmatic Operations

In [6]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [5]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [7]:
a1-a2

array([-5, -5, -5, -5, -5])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [ ]:
Broadcasting

In [16]:
l=[1,2,3,4,5]
arr=np.array(l)
arr+10

array([11, 12, 13, 14, 15])

In [18]:
arr=np.arange(1,21).reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:

Deep & Shallow Copy


In [20]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice=a[:4]
slice

array([1, 2, 3, 4])

In [24]:
slice=slice*10
slice

array([210, 220, 230, 240])

In [25]:
a=a[4:6]
a*10

array([50, 60])

In [27]:
b=a.copy()
b[0]=99
b

array([99,  6])

In [30]:
a

array([5, 6])

In [ ]:

Matrix Operation


In [38]:
A=np.array([[1,2],[3,4]])
B=np.array([[3,7],[4,8]])

In [39]:
A

array([[1, 2],
       [3, 4]])

In [40]:
B

array([[3, 7],
       [4, 8]])

In [41]:
A @ B

array([[11, 23],
       [25, 53]])

In [42]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:

Advanced Array Manipulation


In [43]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [44]:
#vertical staking
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
#horizontal stacking
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
#column stacking
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:

Splitting Array


In [47]:
c=np.arange(1,17).reshape(4,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
h_split=np.hsplit(c,2)
h_split

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [50]:
v_split=np.vsplit(c,4)
v_split

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]